/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * login.java
 *
 * Created on Jun 30, 2023, 10:59:30 PM
 */

/**
 *
 * @author prath
 */
import java.sql.*;
import java.io.*;
import javax.swing.*;
public class login extends javax.swing.JFrame {

    /** Creates new form login */
     
    public login() {
        initComponents();


   }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        label4 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        l4 = new javax.swing.JLabel();
        t2 = new javax.swing.JPasswordField();
        b3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(250, 249, 246));
        jPanel2.setForeground(new java.awt.Color(255, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jPanel2.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));
        jPanel4.setLayout(null);

        label4.setBackground(new java.awt.Color(0, 0, 102));
        label4.setFont(new java.awt.Font("Berlin Sans FB Demi", 3, 48)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label4.setText("Admin Login");
        jPanel4.add(label4);
        label4.setBounds(450, 30, 350, 80);

        t1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jPanel4.add(t1);
        t1.setBounds(570, 180, 290, 80);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PASSWORD :");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(340, 270, 200, 90);

        b2.setBackground(new java.awt.Color(255, 255, 255));
        b2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        b2.setForeground(new java.awt.Color(0, 0, 102));
        b2.setText("NEW ADMIN");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel4.add(b2);
        b2.setBounds(680, 430, 200, 80);

        b1.setBackground(new java.awt.Color(255, 255, 255));
        b1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        b1.setForeground(new java.awt.Color(0, 0, 102));
        b1.setText("LOGIN");
        b1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel4.add(b1);
        b1.setBounds(370, 430, 190, 80);

        l4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        l4.setForeground(new java.awt.Color(255, 255, 255));
        l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l4.setText("USERNAME :");
        jPanel4.add(l4);
        l4.setBounds(350, 180, 180, 90);

        t2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jPanel4.add(t2);
        t2.setBounds(570, 280, 290, 80);

        b3.setBackground(new java.awt.Color(255, 255, 255));
        b3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        b3.setForeground(new java.awt.Color(0, 0, 102));
        b3.setText("EXIT");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel4.add(b3);
        b3.setBounds(1050, 20, 90, 30);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(280, 230, 1170, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1075, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        this.hide();
        add_admin ob=new add_admin();
        ob.setVisible(true);
        ob.show();
}//GEN-LAST:event_b2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        try{
            String u=t1.getText();
            String p=t2.getText();
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con=DriverManager.getConnection("Jdbc:Odbc:tailer");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from admin where uname='"+u+"' and pass='"+p+"'");
            if(rs.next()) {
                JOptionPane.showMessageDialog(this,"Login Succesfull.. Welcome...");
                this.hide();
                mdi ob=new mdi();
                ob.setVisible(true);
                ob.show();
            } else{
                JOptionPane.showMessageDialog(this,"User Not Found... Please Register First...");
            }
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Error:"+e);
        }
}//GEN-LAST:event_b1ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        setVisible(false);
        dispose();
}//GEN-LAST:event_b3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel label4;
    private javax.swing.JTextField t1;
    private javax.swing.JPasswordField t2;
    // End of variables declaration//GEN-END:variables

}
